config/routes.rb
Rails.application.routes.draw do
  resources :lists

  get 'homes/top'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_one_attached :image

    validates :title, presence: true
    validates :body, presence: true
    validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.order(created_at: :desc)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      # flash[:notice]
      redirect_to @list 
    else
      render :new  
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to action: 'show', id: @list 
  end  

  def show
    @list = List.find(params[:id])
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
  end 
  
  

  private

  def list_params
    params.require(:list).permit(:title, :body,:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>トップページ</h1>
<p>hello world</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model: @list, url: list_path(@list.id) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit "保存" %>
<% end %>

app/views/lists/index.html.erb
<h1>投稿一覧（新着順）</h1>
<% @lists.each do |list| %>
    <h4>タイトル</h4>
    <%= link_to list.title, list_path(list.id) %>
    <p>画像</p>
    <% if list.image.attached? %>
        <%= image_tag list.image, size: "200x200" %>
    <% else %>
        <%= image_tag "no_image", size: "200x200" %>
    <% end %>
    <h4>本文</h4>
    <%= list.body %>
<% end %>    

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list, url: lists_path do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>画像</h4>
    <%= f.file_field :image, accept: "image/*" %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '投稿' %>
<% end %>    

app/views/lists/show.html.erb
<h1>詳細画面</h1>
<h4>タイトル：<%= @list.title %></h4>
<h4>本文：<%= @list.body %></h4>
<p>画像</p>
<% if @list.image.attached? %>
    <%= image_tag @list.image, size: "200x200" %>
<% else %>
    <%= image_tag "no_image", size: "200x200" %>
<% end %>

<%= link_to "編集", edit_list_path(@list.id) %>
<%= link_to "削除", list_path(@list.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>